#!/usr/bin/env node
/**
 * Webview 向け TypeScript の CommonJS 出力を、外部依存なしでブラウザ実行可能な
 * IIFE に変換する。tsc 後に scripts/verify.sh と npm run compile から呼ばれる。
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
// 取り込む CJS ソース。ファイル間 import がないことが前提 (共通の exports に積み上げる)。
const SRCS = [
    path.join(ROOT, 'dist', 'webview', 'waveform', 'waveformRenderer.js'),
    path.join(ROOT, 'dist', 'webview', 'draw', 'canvasDrawers.js'),
];
const OUT_DIR = path.join(ROOT, 'dist', 'webview');
const OUT = path.join(OUT_DIR, 'comparisonWaveform.js');
const RUNTIME_ENTRY = path.join(ROOT, 'dist', 'webview', 'runtime', 'comparisonEntry.js');
const RUNTIME_OUT = path.join(OUT_DIR, 'comparisonRuntime.js');

// window 経由で webview の renderScript IIFE から呼ばれる関数の一覧。
// 新しい webview 公開関数を追加したらここに足す。
const EXPORTED_TO_WINDOW = [
    'renderWaveformPipeline',
    'paintLoopRegion',
    'formatHz',
    'dbToRgb',
    'drawWaveformAmplitudeAxis',
    'drawSpectrogramAxes',
    'drawSpectrumLine',
    'drawSpectrumAxes',
];

for (const src of SRCS) {
    if (!fs.existsSync(src)) {
        console.error(`build-webview: source not found: ${src}`);
        console.error('Run `npm run compile` (tsc) first so this script has CJS input.');
        process.exit(1);
    }
}

const concatenatedCjs = SRCS
    .map((src) => `        // --- ${path.relative(ROOT, src)} ---\n${fs.readFileSync(src, 'utf8')}`)
    .join('\n');

const windowAssignments = EXPORTED_TO_WINDOW
    .map((name) => `        if (typeof exports.${name} === 'function') { window.${name} = exports.${name}; }`)
    .join('\n');

const wrapped = `// AUTO-GENERATED by scripts/build-webview.js — do not edit by hand.
// Sources: src/webview/waveform/waveformRenderer.ts, src/webview/draw/canvasDrawers.ts
(function () {
    'use strict';
    const exports = {};
${concatenatedCjs}
${windowAssignments}
})();
`;

if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
}
fs.writeFileSync(OUT, wrapped);
console.log(`build-webview: wrote ${path.relative(ROOT, OUT)} (${wrapped.length} bytes)`);

function moduleId(filePath) {
    return path.relative(path.join(ROOT, 'dist'), filePath).split(path.sep).join('/');
}

function resolveRelativeModule(importer, request) {
    const unresolved = path.resolve(path.dirname(importer), request);
    const candidates = [unresolved, `${unresolved}.js`, path.join(unresolved, 'index.js')];
    const resolved = candidates.find((candidate) => fs.existsSync(candidate));
    if (!resolved) {
        throw new Error(`build-webview: cannot resolve ${request} from ${path.relative(ROOT, importer)}`);
    }
    return resolved;
}

function collectRuntimeModules(entryPath) {
    const modules = new Map();
    function visit(filePath) {
        const id = moduleId(filePath);
        if (modules.has(id)) { return; }
        let source = fs.readFileSync(filePath, 'utf8');
        const dependencies = [];
        source = source.replace(/require\((['"])(\.\.?\/[^'"]+)\1\)/gu, (_match, _quote, request) => {
            const dependency = resolveRelativeModule(filePath, request);
            dependencies.push(dependency);
            return `require(${JSON.stringify(moduleId(dependency))})`;
        });
        modules.set(id, source);
        dependencies.forEach(visit);
    }
    visit(entryPath);
    return modules;
}

if (!fs.existsSync(RUNTIME_ENTRY)) {
    console.error(`build-webview: source not found: ${RUNTIME_ENTRY}`);
    console.error('Run `npm run compile` (tsc) first so this script has CommonJS input.');
    process.exit(1);
}

const runtimeModules = collectRuntimeModules(RUNTIME_ENTRY);
const runtimeFactories = Array.from(runtimeModules, ([id, source]) =>
    `${JSON.stringify(id)}: function (module, exports, require) {\n${source}\n}`,
).join(',\n');
const runtimeWrapped = `// AUTO-GENERATED by scripts/build-webview.js — do not edit by hand.
// Entry: src/webview/runtime/comparisonEntry.ts
(function () {
    'use strict';
    const modules = {
${runtimeFactories}
    };
    const cache = Object.create(null);
    function requireModule(id) {
        if (cache[id]) { return cache[id].exports; }
        const factory = modules[id];
        if (!factory) { throw new Error('Unknown Webview runtime module: ' + id); }
        const module = { exports: {} };
        cache[id] = module;
        factory(module, module.exports, requireModule);
        return module.exports;
    }
    requireModule(${JSON.stringify(moduleId(RUNTIME_ENTRY))});
})();
`;

fs.writeFileSync(RUNTIME_OUT, runtimeWrapped);
console.log(`build-webview: wrote ${path.relative(ROOT, RUNTIME_OUT)} (${runtimeWrapped.length} bytes)`);
