#!/usr/bin/env node
/**
 * waveformRenderer.ts のコンパイル出力 (CommonJS) を webview の <script src>
 * から直接読める IIFE に変換し、dist/webview/comparisonWaveform.js を生成する。
 *
 * 元の media/comparisonWaveform.js (手書きミラー) を置き換える目的の単一ソース化。
 * 依存追加なし。 tsc 後に scripts/verify.sh と npm run compile から呼ばれる。
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
// 取り込む CJS ソース。ファイル間 import がないことが前提 (共通の exports に積み上げる)。
const SRCS = [
    path.join(ROOT, 'dist', 'webview', 'waveform', 'waveformRenderer.js'),
    path.join(ROOT, 'dist', 'webview', 'draw', 'canvasDrawers.js'),
];
const OUT_DIR = path.join(ROOT, 'dist', 'webview');
const OUT = path.join(OUT_DIR, 'comparisonWaveform.js');

// window 経由で webview の renderScript IIFE から呼ばれる関数の一覧。
// 新しい webview 公開関数を追加したらここに足す。
const EXPORTED_TO_WINDOW = [
    'renderWaveformPipeline',
    'paintLoopRegion',
    'formatHz',
    'dbToRgb',
    'drawWaveformAmplitudeAxis',
    'drawSpectrogramAxes',
    'drawSpectrumLine',
    'drawSpectrumAxes',
];

for (const src of SRCS) {
    if (!fs.existsSync(src)) {
        console.error(`build-webview: source not found: ${src}`);
        console.error('Run `npm run compile` (tsc) first so this script has CJS input.');
        process.exit(1);
    }
}

const concatenatedCjs = SRCS
    .map((src) => `        // --- ${path.relative(ROOT, src)} ---\n${fs.readFileSync(src, 'utf8')}`)
    .join('\n');

const windowAssignments = EXPORTED_TO_WINDOW
    .map((name) => `        if (typeof exports.${name} === 'function') { window.${name} = exports.${name}; }`)
    .join('\n');

const wrapped = `// AUTO-GENERATED by scripts/build-webview.js — do not edit by hand.
// Sources: src/webview/waveform/waveformRenderer.ts, src/webview/draw/canvasDrawers.ts
(function () {
    'use strict';
    const exports = {};
${concatenatedCjs}
${windowAssignments}
})();
`;

if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
}
fs.writeFileSync(OUT, wrapped);
console.log(`build-webview: wrote ${path.relative(ROOT, OUT)} (${wrapped.length} bytes)`);
