#!/usr/bin/env node
const path = require('node:path');
const esbuild = require('esbuild');

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'dist', 'webview');
const options = {
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    banner: { js: '// AUTO-GENERATED by scripts/build-webview.js — do not edit by hand.' },
    logLevel: 'info',
};

esbuild.buildSync({
    ...options,
    stdin: {
        contents: `import { renderWaveformPipeline, paintLoopRegion } from './dist/webview/waveform/waveformRenderer.js';
window.renderWaveformPipeline = renderWaveformPipeline;
window.paintLoopRegion = paintLoopRegion;`,
        resolveDir: ROOT,
        sourcefile: 'waveformWindow.js',
    },
    outfile: path.join(OUT_DIR, 'comparisonWaveform.js'),
});
for (const [entry, output] of [
    ['comparisonEntry', 'comparisonRuntime'],
    ['staticHost', 'staticHost'],
]) {
    esbuild.buildSync({
        ...options,
        entryPoints: [path.join(OUT_DIR, 'runtime', `${entry}.js`)],
        outfile: path.join(OUT_DIR, `${output}.js`),
    });
}
